version: '3.9'

services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000" # Expondo API em http://localhost:8000
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000" # Expondo frontend em http://localhost:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev

volumes:
  db_data:
